export const facts = [
  "La déshydratation peut toucher même une peau grasse. Le sébum n'est pas de l'eau.",
  "L'indice UV en Côte d'Ivoire atteint 8 à 12 toute l'année, même par temps nuageux.",
  "Le zinc réduit la production de sébum en inhibant directement les glandes sébacées.",
  "Le moringa ivoirien contient 7 fois plus de vitamine C que l'orange.",
  "Une peau noire produit plus de mélanine, mais reste sensible aux dommages UV.",
  "Le bissap est l'un des antioxydants les plus puissants disponibles en Côte d'Ivoire.",
  "La chaleur tropicale dilate les pores et stimule la production de sébum de 30%.",
  "La niacinamide agit en 2 semaines pour réduire visiblement les pores dilatés.",
  "L'hyperpigmentation post-inflammatoire est le problème n°1 des peaux africaines.",
  "Boire 2L d'eau par jour améliore visiblement l'éclat cutané en moins de 3 semaines.",
  "L'attiéké fermenté contient des probiotiques naturels bénéfiques pour la peau.",
  "La papaye contient de la papaïne, une enzyme qui exfolie naturellement les cellules mortes.",
  "Le SPF50+ doit être appliqué même par temps nuageux en Côte d'Ivoire.",
  "La vitamine C inhibe la tyrosinase, l'enzyme responsable des taches pigmentaires.",
  "Une routine de 3 étapes bien choisies vaut mieux que 10 étapes mal adaptées.",
  "L'avocat est riche en acides gras oméga-9 qui renforcent la barrière cutanée.",
  "Le gingembre frais possède des propriétés anti-inflammatoires bénéfiques pour l'acné.",
  "La sueur excessive en climat tropical peut aggraver l'acné si le visage n'est pas nettoyé.",
  "Le centella asiatica stimule la production de collagène et répare la barrière cutanée.",
  "Les peaux foncées cicatrisent plus lentement mais ont un risque de cancer cutané plus faible.",
  "L'acide hyaluronique peut retenir jusqu'à 1000 fois son poids en eau dans la peau.",
  "Le rétinol accélère le renouvellement cellulaire mais doit toujours être utilisé le soir.",
  "La noix de cajou ivoirienne est l'une des plus riches en zinc parmi les fruits à coque.",
  "Dormir 7 à 8 heures par nuit réduit visiblement les cernes et améliore l'éclat cutané.",
  "Le stress augmente le cortisol, une hormone qui stimule directement les glandes sébacées.",
  "L'eau de coco est une boisson naturellement isotonique, idéale pour hydrater la peau.",
  "La pollution urbaine d'Abidjan génère des radicaux libres qui dégradent le collagène.",
  "Les antioxydants alimentaires protègent les cellules cutanées des dommages UV.",
  "La peau se régénère principalement entre 22h et 2h du matin. Le soin de nuit est crucial.",
  "L'acide salicylique est liposoluble, il pénètre dans les pores gras pour les déboucher.",
  "Le collagène représente 75% des protéines de la peau. Sa synthèse diminue de 1% par an après 25 ans.",
  "Le karité ivoirien contient des insaponifiables qui réparent la barrière cutanée en profondeur.",
  "Une exposition de 20 minutes au soleil suffit à déclencher la mélanogenèse sur une peau foncée.",
  "Le microbiome cutané joue un rôle clé dans la protection contre les bactéries de l'acné.",
  "La peau se renouvelle complètement en environ 28 jours.",
];

export const citations = [
  "Votre peau raconte une histoire unique.",
  "Comprendre sa peau, c'est reprendre confiance en soi.",
  "Chaque détail cutané compte. DermaCI les analyse tous.",
  "Des soins pensés pour vous, pour votre climat, pour votre vie.",
  "Une meilleure peau commence par une meilleure compréhension.",
  "DermaCI analyse votre peau avec la précision d'un dermatologue.",
  "Votre éclat naturel mérite d'être révélé, pas masqué.",
  "Prendre soin de sa peau, c'est prendre soin de soi.",
  "Votre peau mérite des conseils adaptés à votre réalité ivoirienne.",
  "La science au service de votre beauté naturelle.",
  "Chaque analyse est un pas de plus vers la peau que vous méritez.",
  "Votre confiance commence par une peau que vous comprenez.",
  "DermaCI : parce que votre peau mérite mieux que des conseils génériques.",
  "Une peau saine, c'est une vie qui rayonne.",
  "Vous n'avez pas à subir votre peau. Vous pouvez la comprendre et l'aimer.",
  "Les meilleurs soins sont ceux qui sont adaptés à qui vous êtes vraiment.",
  "Votre beauté ivoirienne mérite une expertise qui la comprend.",
  "Chaque peau est unique. Chaque analyse DermaCI l'est aussi.",
  "Prenez soin de votre peau aujourd'hui, elle s'en souviendra demain.",
  "La connaissance de sa peau est le premier actif beauté qui ne coûte rien.",
  "Votre peau est le reflet de votre santé globale. Prenez-en soin avec intention.",
  "DermaCI ne vous donne pas juste des conseils. Il vous donne une compréhension.",
  "La beauté ivoirienne est riche, diverse et puissante. Elle mérite des soins à sa hauteur.",
  "Chaque analyse rapproche votre peau de son meilleur état naturel.",
  "Vous faites le bon choix en cherchant à comprendre votre peau plutôt qu'à la masquer.",
];

export const quizQuestions = [
  { q: "Quel actif réduit le plus efficacement les pores dilatés ?", o: ["Vitamine C", "Niacinamide", "Rétinol", "Collagène"], a: 1 },
  { q: "Quel fruit ivoirien est le plus riche en vitamine C ?", o: ["Mangue", "Ananas", "Goyave", "Orange"], a: 2 },
  { q: "En Côte d'Ivoire, l'indice UV moyen est de :", o: ["2 à 4", "5 à 7", "8 à 12", "13 à 15"], a: 2 },
  { q: "Le zinc est particulièrement utile pour :", o: ["Hydrater la peau", "Réduire le sébum", "Éclaircir le teint", "Lisser les rides"], a: 1 },
  { q: "Quel aliment ivoirien est très riche en antioxydants ?", o: ["Attiéké", "Alloco", "Bissap", "Placali"], a: 2 },
  { q: "Quel actif est indispensable le matin en Côte d'Ivoire ?", o: ["Rétinol", "AHA", "SPF 50+", "Acide salicylique"], a: 2 },
  { q: "La vitamine C agit sur la peau principalement en :", o: ["Hydratant les cellules", "Inhibant la mélanine", "Dilatant les pores", "Augmentant le sébum"], a: 1 },
  { q: "Quel oligo-élément est essentiel à la synthèse du collagène ?", o: ["Fer", "Zinc", "Cuivre", "Magnésium"], a: 2 },
  { q: "Le moringa contient combien de fois plus de vitamine C que l'orange ?", o: ["2 fois", "4 fois", "7 fois", "10 fois"], a: 2 },
  { q: "L'hyperpigmentation post-inflammatoire est causée par :", o: ["Le froid", "Une réaction inflammatoire", "La déshydratation", "Le vent"], a: 1 },
  { q: "Quel actif pénètre dans les pores gras pour les déboucher ?", o: ["Acide hyaluronique", "Acide salicylique", "Niacinamide", "Vitamine E"], a: 1 },
  { q: "L'acide hyaluronique peut retenir combien de fois son poids en eau ?", o: ["10 fois", "100 fois", "500 fois", "1000 fois"], a: 3 },
  { q: "À quelle heure la peau se régénère-t-elle principalement ?", o: ["18h à 20h", "22h à 2h", "6h à 8h", "12h à 14h"], a: 1 },
  { q: "Quel fruit ivoirien est riche en acides gras oméga-9 ?", o: ["Mangue", "Ananas", "Avocat", "Papaye"], a: 2 },
  { q: "Quel actif doit être utilisé le soir uniquement ?", o: ["Niacinamide", "Vitamine C", "Rétinol", "SPF 50+"], a: 2 },
  { q: "Quelle hormone provoque une augmentation du sébum sous stress ?", o: ["Insuline", "Cortisol", "Mélatonine", "Adrénaline"], a: 1 },
  { q: "Le gingembre frais est particulièrement utile pour :", o: ["Hydrater la peau sèche", "Lutter contre l'acné inflammatoire", "Réduire les taches", "Fermer les pores"], a: 1 },
  { q: "Quelle boisson naturelle ivoirienne hydrate la peau de l'intérieur ?", o: ["Jus de mangue sucré", "Eau de coco", "Jus d'ananas industriel", "Café"], a: 1 },
  { q: "La pollution urbaine agit sur la peau en :", o: ["Hydratant les cellules", "Produisant des radicaux libres", "Réduisant le sébum", "Uniformisant le teint"], a: 1 },
  { q: "Quel fruit contient de la papaïne, une enzyme exfoliante naturelle ?", o: ["Mangue", "Goyave", "Papaye", "Ananas"], a: 2 },
  { q: "Quelle est la principale cause d'hyperpigmentation en Côte d'Ivoire ?", o: ["Le froid", "L'exposition aux UV intenses", "La pluie", "Le vent harmattan"], a: 1 },
  { q: "Le centella asiatica est surtout connu pour :", o: ["Réduire le sébum", "Stimuler le collagène", "Exfolier la peau", "Blanchir le teint"], a: 1 },
  { q: "Quel minéral est particulièrement abondant dans la noix de cajou ivoirienne ?", o: ["Fer", "Calcium", "Zinc", "Potassium"], a: 2 },
  { q: "La peau grasse peut-elle être déshydratée ?", o: ["Non jamais", "Oui c'est fréquent", "Seulement en hiver", "Seulement chez les hommes"], a: 1 },
  { q: "Quel type de peau est le plus fréquent en Côte d'Ivoire ?", o: ["Peau sèche", "Peau normale", "Peau grasse ou mixte", "Peau sensible"], a: 2 },
  { q: "L'acide glycolique appartient à quelle famille d'actifs ?", o: ["BHA", "AHA", "PHA", "Rétinol"], a: 1 },
  { q: "Quel est le rôle principal de la mélanine dans la peau ?", o: ["Hydrater", "Protéger des UV", "Réduire le sébum", "Stimuler le collagène"], a: 1 },
  { q: "Le bissap (hibiscus) est riche en :", o: ["Oméga-3", "Anthocyanines antioxydantes", "Acide salicylique", "Rétinol"], a: 1 },
  { q: "À partir de quel âge le collagène commence-t-il à diminuer ?", o: ["18 ans", "25 ans", "35 ans", "45 ans"], a: 1 },
  { q: "Quel actif est le plus efficace contre les taches noires post-acné ?", o: ["Acide salicylique", "Vitamine C", "Rétinol", "Niacinamide"], a: 1 },
  { q: "La peau se renouvelle complètement en combien de jours ?", o: ["7 jours", "14 jours", "28 jours", "60 jours"], a: 2 },
  { q: "Quel oligo-élément combat particulièrement les radicaux libres ?", o: ["Calcium", "Sélénium", "Sodium", "Phosphore"], a: 1 },
  { q: "Le SPF signifie :", o: ["Sun Protection Filter", "Sun Protection Factor", "Skin Protection Formula", "Solar Protection Fluid"], a: 1 },
  { q: "Quelle vitamine est produite par la peau sous l'effet du soleil ?", o: ["Vitamine A", "Vitamine C", "Vitamine D", "Vitamine E"], a: 2 },
  { q: "Le microbiome cutané joue un rôle dans :", o: ["La couleur de la peau", "La protection contre les bactéries de l'acné", "La production de sébum uniquement", "L'épaisseur de la peau"], a: 1 },
  { q: "Quelle plante africaine est utilisée traditionnellement pour soigner les cicatrices ?", o: ["Moringa", "Karité", "Baobab", "Centella asiatica"], a: 1 },
  { q: "Le beurre de karité est particulièrement efficace pour :", o: ["Exfolier la peau", "Réparer la barrière cutanée sèche", "Réduire l'acné", "Éclaircir le teint"], a: 1 },
  { q: "Quel est le phototype majoritaire en Côte d'Ivoire ?", o: ["Phototype I-II", "Phototype III-IV", "Phototype V-VI", "Phototype VII"], a: 2 },
  { q: "La niacinamide et la vitamine C peuvent-elles être utilisées ensemble ?", o: ["Non jamais", "Oui mais à des moments différents", "Oui toujours ensemble", "Non elles s'annulent totalement"], a: 1 },
  { q: "Quel fruit ivoirien est particulièrement riche en bêta-carotène ?", o: ["Goyave", "Ananas", "Mangue", "Citron"], a: 2 },
];

export const progressMessages = [
  "Analyse de votre type de peau...",
  "Détection des problèmes cutanés...",
  "Étude de la texture et du teint...",
  "Génération de votre routine...",
  "Recommandations ivoiriennes...",
  "Finalisation de votre rapport...",
];